### ISSUE TITLE
ERROR: maximum sequence length is 2047

### ISSUE THREAD

**Issue by minxueric** [Dongwon-Lee/lsgkm#1]
In my input fasta file, the longest sequence is 2047 bps long. However, it seems the gkmtrain doesn't support such a long sequence, it will report error:

ERROR 2016-03-24 16:00:01: maximum sequence length is 2047. 

How to solve this problem?

**Comment by Dongwon-Lee** [comment]
(I copied my response for the recode.)
For efficient memory handling, dynamic memory allocation is not used within the tree search algorithm, and the fixed size array is used instead.  You could either remove (or trim) such sequences, or recompile the gkmsvm by increasing MAX_SEQ_LENGTH defined in libsvm_gkm.h.  I will work on fixing this problem by using pre-allocated memory buffer array later, but this will take some time.

**Comment by Dongwon-Lee** [comment]
It is now producing warning messages instead of errors, and use the first (MAX-SEQ_LENGTH-1) bps.
