### ISSUE TITLE
cross-validation (CV) analysis

### ISSUE THREAD

**Issue by BenxiaHu** [Dongwon-Lee/lsgkm#10]
Hi,
  Do you think it is necesary to perform cross-validation (CV) analysis?

  I am a liitle confused about it.

 Best,

**Comment by Dongwon-Lee** [comment]
Cross-validation is typically used to evaluate the classification performance of a model.  If you have an independent & gold-standard (or experimentally validated) data set for evaluation, you don't really have to perform cross-validation.  In most cases, however, we don't have such data.

**Comment by Dongwon-Lee** [comment]
Since there is no follow-up question related to this, I will close this issue.
