### ISSUE TITLE
cross validation group label

### ISSUE THREAD

**Issue by ZhenCaoJack** [Dongwon-Lee/lsgkm#4]
For the cross validation mode, can I set the CV group labels for input sequences? Just like the function gkmsvm_trainCV in R package gkmSVM.  This will help to compare gkm-svm with other methods.

**Comment by Dongwon-Lee** [comment]
LS-GKM does not support the function. However, it does provide the CV group labels in the outputs. So, you can still compare them with other methods using the group labels generated by LS-GKM.

**Comment by ZhenCaoJack** [comment]
Thanks a lot, this is very helpful.
