### ISSUE TITLE
lsgkm fails with large number of training sequences

### ISSUE THREAD

**Issue by Yorkio** [Dongwon-Lee/lsgkm#5]
I'm trying to run the compiled gkmtrain binary on the fasta files with positive and negative sequences to get a model.
The training files contain 35 000 positive sequences and 240 000 negative sequences. 
However when I start training the process finishes very quickly and in the model file all parameter values are set to nan, and there are no any support vectors.

I've done next observations:
When I subsample around 5000 sequences from each file then everything works fine. 
When I subsample more than 5000 sequences from each file then training fails as described before.

What can be the reason?
Is it expected behavior?

**Comment by Dongwon-Lee** [comment]
Sorry for delayed response. LS-GKM should be able to handle your training set. Large cache memory (>20G) and multi-cores (16 is recommended) will be helpful to reduce the training time significantly. In your case, it seems that there are some short sequences in your training set (Every sequence should be at least L bp, and the default L value is 11bp).  So, I suggest that you first check your training sequences more carefully.  Please let me know how it goes.

**Comment by jingNPU** [comment]
I had the same problem when I used 50000 positive sequences and 50000 negative sequences.  The memory set was 40Gb and 4cores. The lsgkm program can not read all the sequences, I checked my training sequences and found no error.What can be the reason? THANKS!
