### ISSUE TITLE
Potential issue in kmertree_dfs with maximum number of mismatches

### ISSUE THREAD

**Issue by AvantiShri** [Dongwon-Lee/lsgkm#6]
Hello,

The gkm-svm paper states that l-mer pairs with more than d mismatches are not counted ("To increase the speed further, we also introduce an optional parameter mmax, which limits the maximum number of mismatches. By setting mmax smaller than l – k, we only consider l-mer pairs that have at most mmax number of mismatches"). However, in reading the code for kmertree_dfs, I believe there is an execution path that could lead to l-mer pairs with more than m mismatches being counted.

First, note that the number of mismatches is only incremented if the mismatch count is less than d:
https://github.com/Dongwon-Lee/lsgkm/blob/164a4a48f6387e67b5d955db932f8a403de6c321/src/libsvm_gkm.c#L467-L471
This means that the maximum value of an l-mer's mismatch count (as tracked by the code) can only be d.

Next, note that when the dfs reaches the very bottom of the tree, if the last base is match then the mismatch profile always gets updated irrespective of the number of mismatches that have been encountered so far during tree traversal:
https://github.com/Dongwon-Lee/lsgkm/blob/164a4a48f6387e67b5d955db932f8a403de6c321/src/libsvm_gkm.c#L426-L433

However, if the last base is a mismatch, then the mismatch profile will only get updated if the number of mismatches encountered so far during tree traversal is less than d (consistent with the behaviour described in the paper that states only l-mer pairs with <= d mismatches are counted):
https://github.com/Dongwon-Lee/lsgkm/blob/164a4a48f6387e67b5d955db932f8a403de6c321/src/libsvm_gkm.c#L436-L443

Thus, based on the code, it looks like l-mer pairs with more than d mismatches could be treated as though they have exactly d mismatches if the very last base happens to match.

Please let me know if I have misunderstood the code!

**Comment by AvantiShri** [comment]
Never mind, I think I figured it out - looks like kmers with more than d mismatches are dropped out of the next_matching_bases array dynamically. Sorry for the noise!

**Comment by Dongwon-Lee** [comment]
Thanks for the careful review of my code :-).  Yes, the array is dynamically maintained while traversing the tree to make sure that the k-mers with more than d mismatches are not included. - Dongwon
