### ISSUE TITLE
nan values for 10mers

### ISSUE THREAD

**Issue by caleblareau** [Dongwon-Lee/lsgkm#9]
Hi @Dongwon-Lee, I'm running into the following issue for multiple of my models using `lsgkm`. 

First, I train the positives and negative sequences:
```
gkmtrain -T 4 -m 8000 test-positive.fa test-negative.fa test2
```

I think that this gives a reasonable output as `head -15 test.model.out` yields

```
svm_type c_svc
kernel_type wgkm
L 11
k 7
d 3
M 50
H 50
nr_class 2
total_sv 111759
rho 0.392289
label 1 -1
nr_sv 58915 52844
SV
1 ACGCCGGGTTAAGGAATGATTTGGTTTTATTCGGCCAGGAGCTTCAGCGGACTCAAGTCTCAAGAACCGAACTCTCTGAAGACAGAGTTCCTGGCCCTTTTAAGGGTTTACAACCTTTAGGTTCCACGTGAAAGGGTCGTGATAGATTGAGAGCACATGCGTTTAGAGTGGGGTGGGGGGGTTAATCTTTTAACCTCAGGCCTGATCATCAGGGGCACCAGCTGGTCTTGCCACTGACTTCATTCCTGTT
0.9913039432319566 CCTCACTGCTGTCCCCGCCTGTGCCCGAAACCCCCGTTCACGTTCACCGAGAAAACAGACATAAACCCAGCCAGGCACATCCACTAGAATGGCTGTGATTTCAGAAAAGCGGACGTAAGTGCTGCCGAGGAGATGGAGGCGTTGGACCCCCTCGCGCATTGTCGGGGCGGGTGCAGCCGCGGTGCAAAAGGACCTTCCTCAGAAAGTTGAGCACGAAGTTCCCACAGGCCCGGAAGTTCCCCTCCCGGGC
```

However, when I then run the predict for 10mers generate via the python script, I get the following

```
 gkmpredict n10mers.fa test.model.txt test.nr10mers.out 
head test.nr10mers.out 


AAAAAAAAAA	-nan
AAAAAAAAAC	-nan
AAAAAAAAAG	-nan
AAAAAAAAAT	-nan
AAAAAAAACA	-nan
AAAAAAAACC	-nan
AAAAAAAACG	-nan
AAAAAAAACT	-nan
AAAAAAAAGA	-nan
AAAAAAAAGC	-nan
```

Have you encountered this before or do you have any idea what's causing this? Thank you!

**Comment by AvantiShri** [comment]
Hi Caleb, just happened to see this - you may have already figured it out but for what it's worth, the issue is likely that you had L (word length) = 11, meaning predictions are undefined for 10-mers.

**Comment by caleblareau** [comment]
@AvantiShri thanks for leaving this here... I somehow got it working, but I was definitely going to be at risk of finding my own question again sometime this year :) Thanks!
